### ISSUE TITLE
[Question] Could we get an example on how to use `measureControlClasses`? 

### ISSUE THREAD

**Issue by ElSabio97** [ppete2/Leaflet.PolylineMeasure#103]
This is maybe a naive question. We are trying to change the colour of the `measureControl` button but can't figure out how to use the `measureControlClasses`.

**Comment by ppete2** [comment]
You can define a new entry somewhere in the beginning **the .css file**, for example:
```
a.polyline-measure-measureControl {
    background-color:#f88;
}
```
**Important:** this entry has to BEFORE "a.polyline-measure-controlOnBgColor" in the css-file! (otherwise the entries of "a.polyline-measure-measureControl" would always overwrite those of "a.polyline-measure-controlOnBgColor"

Then reference to this class **within the .js** file:
`measureControlClasses: ['polyline-measure-measureControl'],
`
